export const asianCountries = [
  { label: "Japan", value: "Japan" },
  { label: "South Korea", value: "South_Korea" },
  { label: "India", value: "India" },
  { label: "China", value: "China" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Thailand", value: "Thailand" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Philippines", value: "Philippines" },
  { label: "Bangladesh", value: "Bangladesh" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "Saudi Arabia", value: "Saudi_Arabia" },
  { label: "United Arab Emirates", value: "United_Arab_Emirates" },
  { label: "Singapore", value: "Singapore" },
  { label: "Nepal", value: "Nepal" },
  { label: "Sri Lanka", value: "Sri_Lanka" },
  { label: "Myanmar", value: "Myanmar" },
  { label: "Kazakhstan", value: "Kazakhstan" },
  { label: "Uzbekistan", value: "Uzbekistan" },
  { label: "Qatar", value: "Qatar" },
];
